services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports:
      - "80:80"
    networks:
      - agent_poc_network
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
      args:
        IMPORT_ZSCALER_CERT: ${IMPORT_ZSCALER_CERT:-false}
    ports:
      - "8888:8888"
    networks:
      - agent_poc_network
  ingestion_server:
    build:
      context: ./ingestion_server
      args:
        IMPORT_ZSCALER_CERT: ${IMPORT_ZSCALER_CERT:-false}
    ports:
      - "8889:8888"
    networks:
      - agent_poc_network
    volumes:
      - ./uploads:/data
    command: ["-upload-dir=/data"]
  collector1:
    build:
      context: ./collector
      args:
        IMPORT_ZSCALER_CERT: ${IMPORT_ZSCALER_CERT:-false}
    image: collector:test
    networks:
      - agent_poc_network
    command: ["--addr", "web:8888", "--source", "collector1"]
    depends_on:
      - web
  collector2:
    build:
      context: ./collector
      args:
        IMPORT_ZSCALER_CERT: ${IMPORT_ZSCALER_CERT:-false}
    image: collector:test
    networks:
      - agent_poc_network
    command: ["--addr", "web:8888", "--source", "collector2"]
    depends_on:
      - web
  switch1:
    image: trnecka/mock_server:latest
    networks:
      - agent_poc_network
    command: ["run","-m", "brocade_switch","-p", "2222"]
    ports:
      - "2222:2222"
  switch2:
    image: trnecka/mock_server:latest
    networks:
      - agent_poc_network
    command: ["run","-m", "brocade_switch_9","-p", "2222"]
    ports:
      - "2223:2222"
networks:
  agent_poc_network: {}