mappers:
  switchshow:
    # case 1 - just a match without capture group - result will be stored as if normal endpoint was used
    # case 2 - capture group without name - value of the cature group value will be used as key in the object
    # case 3 - capture group with name - name will be used as key in hte object and capture group value as subkey
    pattern: "^fosexec_--fid_(?P<vf_switches>\\d+)_-cmd_switchshow$"
  fabricshow:
    pattern: "^fosexec_--fid_(?P<vf_switches>\\d+)_-cmd_fabricshow$"
  agshow:
    pattern: "^fosexec_--fid_(?P<vf_switches>\\d+)_-cmd_agshow$"
extractors:
  version:
    fabric_os:
      method: match_group
      pattern: "(?m)^Fabric OS:\\s*(.+)$"
    kernel:
      method: match_group
      pattern: "(?m)^Kernel:\\s*(.+)$"
  switchshow:
    name:
      method: match_group
      pattern: "(?m)^switchName:\\s*(.+)$"
    mode:
      method: match_group
      pattern: "(?m)^switchMode:\\s*(.+)$"
    role:
      method: match_group
      pattern: "(?m)^switchRole:\\s*(.+)$"
    ports:
      method: match_group_all
      pattern: "(?m)^\\s*(?P<index>\\d+)\\s*(?P<slot>\\d+)\\s*(?P<port>\\d+)\\s*(?P<address>[\\d|-]+)\\s*(?P<media>\\S+)\\s*(?P<speed>\\S+)\\s*(?P<state>\\S+)\\s*(?P<protocol>\\S+)\\s*(?P<description>.*)$"
  fabricshow:
    fabric_name:
      method: match_group
      pattern: "(?m)^Fabric Name:\\s*(.+)$"
    fabric:
      method: match_group_all
      pattern: "(?m)^\\s*(?P<switch_domain>\\d+):\\s+(?P<switch_port_did>\\S+)\\s+(?P<switch_wwn>\\S+)\\s+(?P<switch_ip_addr>\\S+)\\s+(?P<switch_fc_ip_addr>\\S+)\\s+>?\\\"(?P<switch_name>[^\\\"]+)\\\"$"
  agshow:
    access_gateways:
      method: match_group_all
      pattern: "(?m)^\\s*(?P<wwn>\\S+)\\s+(?P<ports_count>\\d+)\\s+(?P<ip_addr>\\S+)\\s+(?P<fabric_os>\\S+)\\s+(?P<connection>\\S+)\\s+(?P<name>\\S+)$"
  licenseshow:
    license:
      method: match_group
      pattern: "(?s)^\\s*(.*?)\\s*$"
    license2:
      method: match_group_all
      pattern: "(?m)^(?P<hash>[A-Za-z0-9]+):\n(?P<code>(?:    .+\n?)+)$"
  # age:
  #   method: match_group
  #   pattern: "(?m)^Age:\\s*(\\d+)$"
  # metadata:
  #   method: parse_json
  #   path: "$.info.meta"  # path is optional, used by JSON extractor