FROM golang:1.23-alpine AS build

COPY zscaler-root-ca.crt /usr/local/share/ca-certificates/zscaler-root-ca.crt
RUN update-ca-certificates

WORKDIR /app

COPY . .

RUN go mod download

RUN env CGO_ENABLED=0 GOOS=windows go build -o collector.exe
RUN env CGO_ENABLED=0 GOOS=linux go build -o collector


FROM scratch AS bin
COPY --from=build /app/collector* /